/** Common ServiceNow variable types */
export const SN_VARIABLE_TYPES = {
  SINGLE_LINE_TEXT: "6",
  MULTI_LINE_TEXT: "7",
  CHECK_BOX: "1",
  SELECT_BOX: "2",
  MULTIPLE_CHOICE: "3",
  NUMERIC_SCALE: "4",
  REFERENCE: "8",
  DATE: "9",
  DATE_TIME: "10",
  LABEL: "11",
  BREAK: "12",
  MACRO: "14",
  UI_PAGE: "15",
  WIDE_SINGLE_LINE: "16",
  LOOKUP_SELECT_BOX: "18",
  CONTAINER_START: "19",
  CONTAINER_END: "20",
  LIST_COLLECTOR: "21",
  LOOKUP_MULTIPLE_CHOICE: "22",
  HTML: "23",
  CONTAINER_SPLIT: "24",
  MASKED: "25",
  EMAIL: "26",
  URL: "27",
  IP_ADDRESS: "28",
  DURATION: "29",
  REQUESTED_FOR: "33",
} as const;

/** Common ServiceNow tables */
export const SN_TABLES = {
  CATALOG_ITEM: "sc_cat_item",
  CATALOG_VARIABLE: "item_option_new",
  CATALOG_VARIABLE_SET: "item_option_new_set",
  BUSINESS_RULE: "sys_script",
  CLIENT_SCRIPT: "sys_script_client",
  UI_POLICY: "sys_ui_policy",
  UI_POLICY_ACTION: "sys_ui_policy_action",
  SCRIPT_INCLUDE: "sys_script_include",
  FLOW: "sys_hub_flow",
  SUBFLOW: "sys_hub_sub_flow",
  UPDATE_SET: "sys_update_set",
  NOTIFICATION: "sysevent_email_action",
  RECORD_PRODUCER: "sc_cat_item_producer",
  ATF_TEST: "sys_atf_test",
  ATF_TEST_SUITE: "sys_atf_test_suite",
  ATF_STEP: "sys_atf_step",
  DICTIONARY: "sys_dictionary",
  SCOPE: "sys_scope",
} as const;
