"""add story attachments

Revision ID: 35fa009f15f0
Revises: a7ee9eae5ad8
Create Date: 2026-04-16 19:52:28.754268
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35fa009f15f0'
down_revision: Union[str, None] = 'a7ee9eae5ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_attachments_organization_id'), 'story_attachments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_story_attachments_story_id'), 'story_attachments', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_attachments_story_id'), table_name='story_attachments')
    op.drop_index(op.f('ix_story_attachments_organization_id'), table_name='story_attachments')
    op.drop_table('story_attachments')
    # ### end Alembic commands ###
