"""add ai gateway, agent memory, and connector models

Revision ID: 9b6e1481b41c
Revises: cd5b71fde81c
Create Date: 2026-04-16 10:22:45.770128
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

revision: str = '9b6e1481b41c'
down_revision: Union[str, None] = 'cd5b71fde81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('default_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_cached_input', sa.Float(), nullable=False),
    sa.Column('fallback_model_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['ai_model_configs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_model_config_org_slug')
    )
    op.create_index(op.f('ix_ai_model_configs_organization_id'), 'ai_model_configs', ['organization_id'], unique=False)
    op.create_table('ai_monthly_spend',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('budget_limit_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'year_month', 'provider', 'model', name='uq_ai_monthly_spend')
    )
    op.create_index(op.f('ix_ai_monthly_spend_organization_id'), 'ai_monthly_spend', ['organization_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'platform', name='uq_connector_org_platform')
    )
    op.create_index(op.f('ix_connectors_organization_id'), 'connectors', ['organization_id'], unique=False)
    op.create_table('ai_routing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_category', sa.String(length=100), nullable=True),
    sa.Column('match_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('match_prompt_slugs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_config_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_config_id'], ['ai_model_configs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_routing_rules_organization_id'), 'ai_routing_rules', ['organization_id'], unique=False)
    op.create_table('connector_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('platform_template', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint_path', sa.String(length=500), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('headers_template', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body_template', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'slug', name='uq_action_connector_slug')
    )
    op.create_index(op.f('ix_connector_actions_connector_id'), 'connector_actions', ['connector_id'], unique=False)
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('source_job_id', sa.UUID(), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_job_id'], ['agent_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_organization_id'), 'agent_memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_memories_project_id'), 'agent_memories', ['project_id'], unique=False)
    op.create_table('ai_request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prompt_slug', sa.String(length=200), nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('model_config_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.id'], ),
    sa.ForeignKeyConstraint(['model_config_id'], ['ai_model_configs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['agent_prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_logs_created_at'), 'ai_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_organization_id'), 'ai_request_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_request_logs_organization_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_created_at'), table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    op.drop_index(op.f('ix_agent_memories_project_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_organization_id'), table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_index(op.f('ix_connector_actions_connector_id'), table_name='connector_actions')
    op.drop_table('connector_actions')
    op.drop_index(op.f('ix_ai_routing_rules_organization_id'), table_name='ai_routing_rules')
    op.drop_table('ai_routing_rules')
    op.drop_index(op.f('ix_connectors_organization_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_ai_monthly_spend_organization_id'), table_name='ai_monthly_spend')
    op.drop_table('ai_monthly_spend')
    op.drop_index(op.f('ix_ai_model_configs_organization_id'), table_name='ai_model_configs')
    op.drop_table('ai_model_configs')
    # ### end Alembic commands ###
