"""connector overhaul and epic support

Revision ID: a7ee9eae5ad8
Revises: 9b6e1481b41c
Create Date: 2026-04-16 10:50:58.421558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7ee9eae5ad8'
down_revision: Union[str, None] = '9b6e1481b41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('instance_label', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('uq_connector_org_platform'), 'connectors', type_='unique')
    op.add_column('projects', sa.Column('connector_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'connectors', ['connector_id'], ['id'])
    op.add_column('user_stories', sa.Column('parent_story_id', sa.UUID(), nullable=True))
    op.add_column('user_stories', sa.Column('story_type', sa.String(length=20), server_default='story', nullable=False))
    op.add_column('user_stories', sa.Column('figma_node_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_stories_parent_story_id'), 'user_stories', ['parent_story_id'], unique=False)
    op.create_foreign_key(None, 'user_stories', 'user_stories', ['parent_story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stories', type_='foreignkey')
    op.drop_index(op.f('ix_user_stories_parent_story_id'), table_name='user_stories')
    op.drop_column('user_stories', 'figma_node_id')
    op.drop_column('user_stories', 'story_type')
    op.drop_column('user_stories', 'parent_story_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'connector_id')
    op.create_unique_constraint(op.f('uq_connector_org_platform'), 'connectors', ['organization_id', 'platform'], postgresql_nulls_not_distinct=False)
    op.drop_column('connectors', 'instance_label')
    # ### end Alembic commands ###
