"""add control plane models

Revision ID: cd5b71fde81c
Revises: 64ec093af124
Create Date: 2026-04-10 14:13:35.093522
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cd5b71fde81c'
down_revision: Union[str, None] = '64ec093af124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('template_format', sa.String(length=20), nullable=False),
    sa.Column('default_variables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_prompt_org_slug')
    )
    op.create_index(op.f('ix_agent_prompts_organization_id'), 'agent_prompts', ['organization_id'], unique=False)
    op.create_table('agent_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('pre_conditions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('post_conditions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_composite', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_skill_org_slug')
    )
    op.create_index(op.f('ix_agent_skills_organization_id'), 'agent_skills', ['organization_id'], unique=False)
    op.create_table('agent_prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sections', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('variables_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['agent_prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_prompt_versions_prompt_id'), 'agent_prompt_versions', ['prompt_id'], unique=False)
    op.create_table('agent_skill_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('sub_skill_id', sa.UUID(), nullable=True),
    sa.Column('prompt_slug', sa.String(length=200), nullable=True),
    sa.Column('input_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('condition', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_policy', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_approval_gate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['agent_skills.id'], ),
    sa.ForeignKeyConstraint(['sub_skill_id'], ['agent_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_skill_steps_skill_id'), 'agent_skill_steps', ['skill_id'], unique=False)
    op.create_table('agent_prompt_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('traffic_weight', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_by_id', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['agent_prompts.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['agent_prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'label', name='uq_prompt_label')
    )
    op.create_index(op.f('ix_agent_prompt_labels_prompt_id'), 'agent_prompt_labels', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_prompt_labels_prompt_id'), table_name='agent_prompt_labels')
    op.drop_table('agent_prompt_labels')
    op.drop_index(op.f('ix_agent_skill_steps_skill_id'), table_name='agent_skill_steps')
    op.drop_table('agent_skill_steps')
    op.drop_index(op.f('ix_agent_prompt_versions_prompt_id'), table_name='agent_prompt_versions')
    op.drop_table('agent_prompt_versions')
    op.drop_index(op.f('ix_agent_skills_organization_id'), table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_index(op.f('ix_agent_prompts_organization_id'), table_name='agent_prompts')
    op.drop_table('agent_prompts')
    # ### end Alembic commands ###
